jobs:
- template: build/uno-ci/build-skia-windows.yml
- template: build/uno-ci/build-android-netcore-windows.yml
- template: .vsts-ci.Linux.yml
- template: .vsts-ci.catalyst.yml
- template: .vsts-ci.iOS.yml
- template: .vsts-ci.Skia.yml
